name = "LegendDSP"
uuid = "e6d7a502-be5c-5049-a927-8d60e566555d"
version = "0.1.0"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
ArraysOfArrays = "65a8f2f4-9b39-5baf-92e2-a9cc46fdf018"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
FunctionChains = "8e6b2b91-af83-483e-ba35-d00930e4cf9b"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PropDicts = "4dc08600-4268-439e-8673-d706fafbb426"
RadiationDetectorDSP = "afd6e06f-c550-5763-af36-7391d39e46ec"
RadiationDetectorSignals = "bf2c0563-65cf-5db2-a620-ceb7de82658c"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Adapt = "1, 2, 3"
ArgCheck = "1, 2"
ArraysOfArrays = "0.4, 0.5, 0.6"
DocStringExtensions = "0.8, 0.9"
FillArrays = "0.7, 0.8, 0.9, 0.10, 0.11, 0.12, 0.13, 1"
FunctionChains = "0.1"
IntervalSets = "0.7"
RadiationDetectorDSP = "0.2.1"
RadiationDetectorSignals = "0.3.3"
Tables = "1.1"
TypedTables = "1.4.3"
Unitful = "1"
julia = "1.6"
